# -*- encoding: utf-8 -*-
#
# Copyright 2015-2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Global parameters about the API itself
#
import os

HOST = os.getenv('API_HOST', '127.0.0.1')
PORT = os.getenv('API_PORT', 5000)
DEBUG = os.getenv('DEBUG', True)

# Database (SQLAlchemy) related parameters
#
DB_USER = os.getenv('DB_USER', 'dci')
DB_PASSWORD = os.getenv('DB_PASSWORD', 'dci')
DB_HOST = os.getenv('DB_HOST', '127.0.0.1')
DB_PORT = os.getenv('DB_PORT', 5432)
DB_NAME = os.getenv('DB_NAME', 'dci')
DEFAULT_SQLALCHEMY_DATABASE_URI = 'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}'.format(
    db_user=DB_USER,
    db_password=DB_PASSWORD,
    db_host=DB_HOST,
    db_port=DB_PORT,
    db_name=DB_NAME,
)  # noqa
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI',
                                    DEFAULT_SQLALCHEMY_DATABASE_URI)

# The following two lines will output the SQL statements
# executed by SQLAlchemy. Useful while debugging and in
# development. Turned off by default
# --------
SQLALCHEMY_ECHO = False
SQLALCHEMY_RECORD_QUERIES = False

SQLALCHEMY_POOL_SIZE = 20
SQLALCHEMY_MAX_OVERFLOW = 0
SQLALCHEMY_NATIVE_UNICODE = True

# Stores configuration, to store files and components
# STORE
STORE_ENGINE = os.getenv('STORE_ENGINE', 'Swift')
STORE_USERNAME = os.getenv('STORE_USERNAME', 'dci')
STORE_PASSWORD = os.getenv('STORE_PASSWORD', 'dci')
STORE_TENANT_NAME = os.getenv('STORE_TENANT_NAME', 'dci')
STORE_HOST = os.getenv('STORE_HOST', '127.0.0.1')
STORE_PORT = os.getenv('STORE_PORT', 5000)
DEFAULT_STORE_AUTH_URL = 'http://{store_host}:{store_port}/v2.0'.format(
    store_host=STORE_HOST,
    store_port=STORE_PORT
)
STORE_AUTH_URL = os.getenv('STORE_AUTH_URL', DEFAULT_STORE_AUTH_URL)
STORE_CONTAINER = os.getenv('STORE_CONTAINER', 'dci_components')
STORE_FILES_CONTAINER = os.getenv('STORE_FILES_CONTAINER', 'dci_components')
STORE_COMPONENTS_CONTAINER = os.getenv('STORE_COMPONENTS_CONTAINER', 'dci_files')

# ZMQ Connection
ZMQ_HOST = os.getenv('ZMQ_HOST', '127.0.0.1')
ZMQ_PORT = os.getenv('ZMQ_PORT', 5557)
DEFAULT_ZMQ_CONN = 'tcp://{zmq_host}:{zmq_port}'.format(
    zmq_host=ZMQ_HOST,
    zmq_port=ZMQ_PORT
)
ZMQ_CONN = os.getenv('ZMQ_CONN', DEFAULT_ZMQ_CONN)

# Logging related parameters
PROD_LOG_FORMAT = '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
DEBUG_LOG_FORMAT = (
        '-' * 80 + '\n' +
        '%(levelname)s at %(asctime)s in %(name)s:\n' +
        '%(message)s\n' +
        '-' * 80
)

LOG_FILE = '/tmp/dci.log'

LAST_UPDATED = 'updated_at'
DATE_CREATED = 'created_at'
ID_FIELD = 'id'
ITEM_URL = ('regex("[\.-a-z0-9]{8}-[-a-z0-9]{4}-'
            '[-a-z0-9]{4}-[-a-z0-9]{4}-[-a-z0-9]{12}")')

ITEM_LOOKUP_FIELD = 'id'
ETAG = 'etag'
URL_PREFIX = 'api'
X_DOMAINS = '*'
X_HEADERS = 'Authorization, Content-Type, If-Match, ETag, X-Requested-With'
MAX_CONTENT_LENGTH = 20 * 1024 * 1024

FILES_UPLOAD_FOLDER = '/var/lib/dci-control-server/files'

# generated by bin/dci-gen-pem-ks-key.py
SSO_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA64PNcZgs1adZG4wPuaTv
fM1r2K0E4Yanp4RHEhcn38yoMZy593jB10ej/i+fLv5CRchpLpUPVl6230ugObie
IU4n5BKwt1Y11Wt65UIIf6K3pDTVX5iaT0u6ISSSMHBMpLo5ndfHQHDoMhiyuIFt
DI/RzFlhayJM5GeNjA/qhDHqd2mDEftJ9RyEYCdnRmFm8juOzdsY3DOqp6FpZqQt
+72TRfEbsYG8RRYHKOzhC4yL+7DebWpJdwBjzFx+CbmQRLUmVmIbY0VtDAfVqfFN
yv0IboebFxlX5mCTijk1k3BU8Xb3+vY5CT8f2OSUM78dfrwyX/0uAMPdBl6e0yae
/JE4TV3WXqstpubVybW2SJQT5MIcLPkD9h6hmD5HV19nPYCd1YfImWr383LEHMmB
lT40f5PcBYlqQqOkZj1lUac62cfNRkNBYbONhTLSbK/hezMH3myIHmw+qctMJZtp
kf7/j0VSQf0f1BIChjXsFfkcDuEeeTXSSxh+I9xIB4uYpDbzUiuSlDk74aRaiB3S
USDOa5hKSVfeIv7bNNMgGJQEXXyBIKfajI1MZCEEAOp/SP66Gj4q4nnNJI6aSh+3
hZ3LTvCbgf1OdidRPayfIBECq/oU9hsfu1oX3sJXYdISqaxBXfyWXSbwt5Rv1HuV
4GdQgMGs8c49SX/5ZUZii3sCAwEAAQ==
-----END PUBLIC KEY-----
"""
SSO_CLIENT_ID = 'dci'
SSO_READ_ONLY_GROUP = 'redhat:employees'

CA_CERT = '/etc/ssl/repo/ca.crt'
CA_KEY = '/etc/ssl/repo/ca.key'

CERTIFICATION_URL = 'https://access.stage.redhat.com/hydra/rest/cwe/xmlrpc/v2'
