#!/bin/sh
# Ensure the dependencies are really installed
pip install -r ${OPENSHIFT_REPO_DIR}/requirements.txt
# NOTE(Gonéri): Extra optional deps to get the /docs working
pip install git+https://github.com/hermannsblum/eve-docs
pip install Flask-Bootstrap


./app-root/repo/dci/cmd/dbsync.py
./app-root/repo/dci/cmd/init_openshift_db.py

#We will use entrypoints when we get rid of Eve, because of version conflict
#between dci (Eve>=0.6)  and Eve-SQLAlchemy (Eve>=0.5,<0.6)
#dci-dbsync
#dci-openshift-dbinit

cd $OPENSHIFT_REPO_DIR/dci/dci_databrowser
HOME=$OPENSHIFT_TMP_DIR scl enable nodejs010 "npm install && node_modules/.bin/gulp build"
