# -*- encoding: utf-8 -*-
#
# Copyright 2015-2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import os

DEBUG = False

LOG_FILE = '/dev/null'

SQLALCHEMY_DATABASE_URI = "postgresql:///%s?host=%s" % (
    'charlesdegaulle', os.path.abspath(os.environ['DCI_DB_DIR'])
)

FILES_UPLOAD_FOLDER = '/tmp/dci-control-server'

SSO_CLIENT_ID = 'dci-cs'
# generated by ./bin/dci-gen-pem-ks-key.py on a local sso server
SSO_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgBH5yRAVT3gkOyUXMIVn
wSB6L/gurcAIAr4OIg83rduY8v7JGG3FL30bFr38dRGBQCWGDUqzeSRg0KVtfUk0
r01CTa8WDvj/A35P8ANhYjZQb6Rx2ibyhTwnm4QSVLeBe424M8ybRgRl9WkAixRO
iNNF2o9uNWJkTFLZ8wCGnYcu/PI8ZQCi/PnFjF+r63id8VOG5eSDrTLZuqbs9L0L
L4w3+R8tgTIUWl2X/Fps760XYl9r3WjAXc8aYiLPqYR6EheoC00QZmGxRbdq8yVt
csnCpzVVAEEaQEwv/Smu9e1L2ObyAp387xjDOTHQZNXMb7TSJuhxyOLQQ3NWO+1o
zQIDAQAB
-----END PUBLIC KEY-----
"""

CA_CERT = '/tmp/ca.crt'
CA_KEY = '/tmp/ca.key'
