# -*- coding: utf-8 -*-
#
# Copyright (C) 2015 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


def domain_configuration():
    uuid_re = ('regex("[-a-z0-9]{8}-[-a-z0-9]{4}-' +
               '[-a-z0-9]{4}-[-a-z0-9]{4}-[-a-z0-9]{12}")')
    name_re = 'regex("[-_\\w\\d]+")'
    domain = {
        'components': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'canonical_project_name': 1,
                    'componenttype': 1,
                    'componenttype_id': 0,
                    'created_at': 1,
                    'data': 1,
                    'etag': 1,
                    'git': 1,
                    'id': 1,
                    'message': 1,
                    'name': 1,
                    'ref': 1,
                    'sha': 1,
                    'title': 1,
                    'updated_at': 1,
                    'url': 1},
                'source': 'Component'},
            'description': {
                'fields': {}, 'general': 'The components.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'canonical_project_name': {
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'componenttype': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'componenttypes'},
                    'type': 'objectid'},
                'componenttype_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'componenttypes'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'data': {
                    'nullable': True,
                    'required': False,
                    'type': 'json',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'git': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'message': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'name': {
                    'maxlength': 255,
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'ref': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'sha': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'title': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'url': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False}}},
        'componenttypes': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'components': 0,
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'name': 1,
                    'updated_at': 1},
                'source': 'Componenttype'},
            'description': {
                'fields': {},
                'general': 'The different type of '
                'components.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'components': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'components'},
                    'type': 'objectid'},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'name': {
                    'maxlength': 255,
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'files': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'auth_field': 'team_id',
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'content': 1,
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'jobstate': 1,
                    'jobstate_id': 0,
                    'md5': 1,
                    'mime': 1,
                    'name': 1,
                    'team': 0,
                    'team_id': 1,
                    'teams': 0,
                    'updated_at': 1},
                'source': 'File'},
            'description': {
                'fields': {},
                'general': 'The output of a command execution. '
                'The file is associated to a '
                'jobstate of a given job.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'content': {
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobstate': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobstates'},
                    'type': 'objectid'},
                'jobstate_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'jobstates'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'md5': {
                    'maxlength': 32,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'mime': {
                    'maxlength': 100,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'name': {
                    'maxlength': 512,
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'team': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'team_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'teams'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'teams': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'jobdefinition_components': {
            'datasource': {
                'default_sort': [('created_at',
                                  1)],
                'projection': {
                    'component': 1,
                    'component_id': 0,
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'jobdefinition': 1,
                    'jobdefinition_id': 0,
                    'updated_at': 1},
                'source': 'JobdefinitionComponent'},
            'description': {
                'fields': {}, 'general': ''},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH',
                             'DELETE',
                             'PUT',
                             'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'component': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'components'},
                    'type': 'objectid'},
                'component_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'components'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobdefinition': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobdefinitions'},
                    'type': 'objectid'},
                'jobdefinition_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'jobdefinitions'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'jobdefinitions': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'components': 1,
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'jobs': 0,
                    'name': 1,
                    'priority': 1,
                    'test': 1,
                    'test_id': 0,
                    'updated_at': 1},
                'source': 'Jobdefinition'},
            'description': {
                'fields': {}, 'general': ''},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'components': {
                    'schema': {
                        'data_relation': {
                            'embeddable': True,
                            'resource': 'components'},
                        'type': 'objectid'},
                    'type': 'list'},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobdefinition_components': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobdefinition_components'},
                    'type': 'objectid'},
                'jobs': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobs'},
                    'type': 'objectid'},
                'name': {
                    'maxlength': 200,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'priority': {
                    'required': False,
                    'type': 'integer',
                    'unique': False},
                'test': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'tests'},
                    'type': 'objectid'},
                'test_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'tests'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'jobs': {
            'auth_field': 'team_id',
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'jobdefinition': 1,
                    'jobdefinition_id': 0,
                    'jobstates': 1,
                    'recheck': 1,
                    'remoteci': 1,
                    'remoteci_id': 0,
                    'team': 1,
                    'team_id': 0,
                    'updated_at': 1},
                'source': 'Job'},
            'description': {
                'fields': {},
                'general': 'A collection of components and a '
                'test ready to associated to a '
                'remoteci to create a new job.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobdefinition': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobdefinitions'},
                    'type': 'objectid'},
                'jobdefinition_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'jobdefinitions'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'jobstates': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobstates'},
                    'type': 'objectid'},
                'recheck': {
                    'required': False,
                    'type': 'boolean',
                    'unique': False},
                'remoteci': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'remotecis'},
                    'type': 'objectid'},
                'remoteci_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'remotecis'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'team': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'team_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'teams'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'jobstates': {
            'auth_field': 'team_id',
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'comment': 1,
                    'created_at': 1,
                    'etag': 1,
                    'files': 0,
                    'id': 1,
                    'job': 1,
                    'job_id': 0,
                    'jobs': 0,
                    'status': 1,
                    'team': 1,
                    'team_id': 0,
                    'updated_at': 1},
                'source': 'Jobstate'},
            'description': {
                'fields': {
                    'comment': 'ongoing: the job is '
                    'still running, '
                    'failure: the job '
                    'has failed and this '
                    'is the last status, '
                    'success: the job '
                    'has been run '
                    'successfully.'},
                'general': 'One of the status during the '
                'execution of a job. The last '
                'one is the last know status.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'comment': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'files': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'files'},
                    'type': 'objectid'},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'job': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobs'},
                    'type': 'objectid'},
                'job_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'jobs'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'status': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'team': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'team_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'teams'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'remotecis': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'auth_field': 'team_id',
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'data': 1,
                    'etag': 1,
                    'id': 1,
                    'jobs': 0,
                    'name': 1,
                    'team': 1,
                    'team_id': 0,
                    'team': 1,
                    'test': 1,
                    'test_id': 0,
                    'updated_at': 1,
                    'user_remotecis': 0},
                'source': 'Remoteci'},
            'description': {
                'fields': {},
                'general': 'The remote CI agent that '
                'process the test.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'data': {
                    'nullable': True,
                    'required': False,
                    'type': 'json',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobs': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobs'},
                    'type': 'objectid'},
                'name': {
                    'maxlength': 255,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'team': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'team_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'teams'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'test': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'tests'},
                    'type': 'objectid'},
                'test_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'tests'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'user_remotecis': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'user_remotecis'},
                    'type': 'objectid'}}},
        'roles': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'name': 1,
                    'updated_at': 1,
                    'user_roles': 0},
                'source': 'Role'},
            'description': {
                'fields': {}, 'general': 'The user roles.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'name': {
                    'maxlength': 100,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'user_roles': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'user_roles'},
                    'type': 'objectid'}}},
        'teams': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'files': 0,
                    'id': 1,
                    'jobs': 0,
                    'name': 1,
                    'remotecis': 1,
                    'updated_at': 1,
                    'users': 0},
                'source': 'Team'},
            'description': {
                'fields': {},
                'general': 'The user team. An user can only be '
                'in one team. All the resource '
                'created by an user are shared with '
                'his/her team members.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'files': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'files'},
                    'type': 'objectid'},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobs': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobs'},
                    'type': 'objectid'},
                'name': {
                    'maxlength': 100,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'remotecis': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'remotecis'},
                    'type': 'objectid'},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'users': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'users'},
                    'type': 'objectid'}}},
        'tests': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'data': 1,
                    'etag': 1,
                    'id': 1,
                    'jobdefinitions': 0,
                    'name': 1,
                    'remotecis': 0,
                    'updated_at': 1},
                'source': 'Test'},
            'description': {
                'fields': {}, 'general': 'A QA test.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'data': {
                    'nullable': True,
                    'required': False,
                    'type': 'json',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'jobdefinitions': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'jobdefinitions'},
                    'type': 'objectid'},
                'name': {
                    'maxlength': 255,
                    'required': True,
                    'type': 'string',
                    'unique': False},
                'remotecis': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'remotecis'},
                    'type': 'objectid'},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False}}},
        'user_remotecis': {
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'remoteci': 1,
                    'remoteci_id': 0,
                    'updated_at': 0,
                    'user': 1,
                    'user_id': 0,
                    'users': 0},
                'source': 'UserRemoteci'},
            'description': {
                'fields': {}, 'general': 'experimental'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'remoteci': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'remotecis'},
                    'type': 'objectid'},
                'remoteci_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'remotecis'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'user': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'users'},
                    'type': 'objectid'},
                'user_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'users'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False}}},
        'user_roles': {
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'role': 1,
                    'role_id': 0,
                    'roles': 0,
                    'updated_at': 1,
                    'user': 1,
                    'user_id': 0,
                    'users': 0},
                'source': 'UserRole'},
            'description': {
                'fields': {},
                'general': 'Relation table between the '
                'users and the roles.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'role': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'roles'},
                    'type': 'objectid'},
                'role_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'roles'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'user': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'users'},
                    'type': 'objectid'},
                'user_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'users'},
                    'required': True,
                    'type': 'objectid',
                    'unique': False}}},
        'users': {
            'additional_lookup': {
                'field': 'name',
                'url': name_re},
            'auth_field': 'team_id',
            'datasource': {
                'default_sort': [('created_at', 1)],
                'projection': {
                    'created_at': 1,
                    'etag': 1,
                    'id': 1,
                    'name': 1,
                    'password': 1,
                    'team': 1,
                    'team_id': 0,
                    'updated_at': 1,
                    'user_remotecis': 0,
                    'user_roles': 0,
                    'roles': 1},
                'source': 'User'},
            'description': {
                'fields': {}, 'general': 'The user list.'},
            'id_field': 'id',
            'item_lookup': True,
            'item_lookup_field': 'id',
            'item_methods': ['PATCH', 'DELETE', 'PUT', 'GET'],
            'item_url': uuid_re,
            'public_item_methods': [],
            'public_methods': [],
            'resource_methods': ['GET', 'POST', 'DELETE'],
            'schema': {
                'created_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'etag': {
                    'maxlength': 40,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'id': {
                    'required': False,
                    'type': 'string',
                    'unique': True},
                'name': {
                    'maxlength': 100,
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'password': {
                    'nullable': True,
                    'required': False,
                    'type': 'string',
                    'unique': False},
                'team': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'team_id': {
                    'data_relation': {
                        'embeddable': False,
                        'resource': 'teams'},
                    'required': False,
                    'type': 'objectid',
                    'unique': False},
                'teams': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'teams'},
                    'type': 'objectid'},
                'updated_at': {
                    'required': False,
                    'type': 'datetime',
                    'unique': False},
                'user_remotecis': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'user_remotecis'},
                    'type': 'objectid'},
                'user_roles': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'user_roles'},
                    'type': 'objectid'},
                'roles': {
                    'data_relation': {
                        'embeddable': True,
                        'resource': 'roles'},
                    'type': 'objectid'}}}}
    return domain
