FROM fedora

RUN dnf update -y
RUN dnf install -y nodejs npm tar bzip2 make freetype fontconfig

WORKDIR /tmp

RUN npm install -g gulp npm-cache
WORKDIR /opt/dci_databrowser

CMD ["gulp", "serve"]
EXPOSE 8000 35729
